# Generated by Django 3.0.8 on 2020-08-08 15:02

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_auto_20200801_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
