# Generated by Django 3.0.8 on 2020-08-13 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0008_note_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('New', 'Yeni'), ('True', 'Evet'), ('False', 'Hayır'), ('Update', 'Update')], default='New', max_length=10),
        ),
        migrations.AlterField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır'), ('Update', 'Update')], max_length=10),
        ),
    ]
